### PR TITLE
Blif parsing fixes

### PR DESCRIPTION
**Pull request by jhol**
This branch fixes 6 crash bugs that were discovered with American Fuzzy Lop, and adds test cases for each bug.

To aid the editing of `blif.cc`, the tab characters have been substituted with spaces. Would it be possible to replace the tabs with either all tabs, or all spaces throughout the project? The auto-replacement-of-8-spaces-with-tabs convention is quite unusual, and is often difficult to configure editors to conform to the convention.

### CODE REVIEW

**Comment by cseed** [comment]
This is fantastic work, thanks!  I will merge it in as soon as travis finishes.  I agree about spaces vs tabs.  I will convert everything to spaces.

**Comment by jhol** [comment]
Cool. I started another test run this morning, this time with ASAN built in, and its picked up a couple more bugs. I'll leave it running for a few days and see what else it digs up.

**Comment by cseed** [comment]
Awesome.  I started a run on the pcf input and found one bug so far.  I committed my afl testcases and a fuzz-pcf make target.  Feel free to submit a pull request for something similar for blif.  Curious, did you create a blif dictionary?

**Comment by jhol** [comment]
@cseed Ok cool. I was going to test the PCF myself.

I found results were quite slow to obtain in the main application - because the first thing arachne-pnr does on startup is parse the chipdb which takes a large fraction of a second on my PC. Therefore, I've been running the tests with the BLIF parser and data model classes extracted into a test executable - doing this gets the execution speed up to ~500 runs/second. At this rate, bugs come in at a much more reasonable rate - though obviously it's not going to find bugs in the router.

I was thinking it might be a good idea to sequence the chipdb loading after parsing the BLIF, and maybe the PCF parsing - if possible. Failing faster would have benefits for normal users also.

**Comment by jhol** [comment]
@cseed Also, yes I do use a dictionary; nothing special, just the directives from the BLIF spec - I found it was somewhat beneficial. I think a better dictionary might have more realistic BLIF statements in it.

**Comment by cseed** [comment]
@jhol I saw remark in the afl perf-tips that the llvm instrumentation had a "persistent" mode for programs with high startup costs.  That might be worth looking into.

Cool.  I thought it might also be worthwhile to include the iCE40 primitive names (SB_DFF, etc.), too.

I agree about loading the chipdb later.  I'll make that change.  Most of the chipdb is the routing tables.  It might be worth loading the main chipdb first and the routing tables just before routing.  Maybe we could find bugs in pack or place that way.

I'm adding support for pnr scritps a bit like Yosys.  That will support things like parsing BLIF and existing without having modify the code.

**Comment by jhol** [comment]
@cseed - if you're looking at llvm instrumentation, I read that llvm integrated a fuzz testing algorithm inspired by AFL. Maybe both can be used together.

**Comment by cseed** [comment]
I was referring to this, from docs/perf_tips.txt:

```
3) Use LLVM instrumentation
---------------------------

When fuzzing slow targets, you can gain 2x performance improvement by using
the LLVM-based instrumentation mode described in llvm_mode/README.llvm. Note
that this mode requires the use of clang and will not work with GCC.

The LLVM mode also offers a "persistent", in-process fuzzing mode that can
work well for certain types of self-contained libraries, and for fast targets,
can offer performance gains up to 5-10x; and a "deferred fork server" mode
that can offer huge benefits for programs with high startup overhead. Both
modes require you to edit the source code of the fuzzed program, but the
changes often amount to just strategically placing a single line or two.
```

From a quick look at REAME.llvm, looks like we can load chipdb once and then iterate over test cases.

**Pull request merged**
