### PR TITLE
Replaced Makefile build system with CMake

### PR DESCRIPTION
**Pull request by jhol**
CMake has various advantages over Makefiles.
* Portability to different platforms
* Generates build scripts for different build systems: GNU Make, Ninja Build, Visual Studio
* Easy compliance with various common patterns.

This branch replaces the Makefile build system with CMake, and adds support for packaging with CPack.

### CODE REVIEW

**Comment by cseed** [comment]
Hi jhol,

Thanks for contributing!  Few comments:
 - test_bv binary should be in tests/.
 - .gitignore is missing cmake products.  I like git status to be clean after building a clean repo.
 - The simpletest target is missing.  I use both simpletest and test as part of my development workflow.  Also, if I have to reconfigure to run all the tests, I will forget to do so and commit untested stuff, I'm sure.  It would be OK to skip the valgrind test if valgrind isn't found.

I'm happy to merge your if you fix these and I don't find anything else.

Any chance you've tested this on Windows?

**Comment by jhol** [comment]
@cseed Thanks for the comments. I'll address these things in the next day or two.

I didn't test windows just yet. I think msys2 would be the way to go to test that out.

**Comment by jhol** [comment]
@cseed I've been working on your comments...

* About `test_bv`. Putting it in `tests/` doesn't really mesh with CMake, because CMake encourages (though does not require) out-of-tree building. If someone is doing an out-of-tree build, it becomes rather ugly to put the executable in the source tree.
* I added `*.cmake` to `.gitignore`
* I made some improvements to the way the dependency programs are detected, and added a `simpletest` target. For now I think it's better to require *valgrind*, because anyone who comes to help with the project really should be giving it the thorough testing treatment.

**Comment by cseed** [comment]
@jhol 
* OK, I can get behind out of source builds.  Can we still put test_bv in $builddir/tests/?  (I didn't check, does arachne-pnr end up in $builddir/bin/?)  
* Thanks!
* While I agree it is better to require valgrind, and I would like to do that, I develop on OSX 10.10 Yosemite and valgrind currently does not support it.  In the meantime, I'm going to need some hack that lets me configure and test without valgrind.

**Comment by jhol** [comment]
@cseed 
* I can't see any clean way of controlling the cmake output directory. Is this important?
* No problem.
* I added a commit that skips the valgrind test (with a warning) if the valgrind is not found.

**Comment by jhol** [comment]
@cseed So what's your verdict on this branch?

My feeling is that while it may not be possible to exactly replicate your existing work-flow with CMake, ultimately it's going to give a much more scalable solution, that will give lots of powerful features and ancillary benefits for free.

Are there any issues that you regards as deal-breaking?

**Comment by cseed** [comment]
@jhol Sorry for taking so long to reply.  Yes, I agree with you.  I want to be a little more comfortable with CMake before I merge the changes into the mainline, so I don't feel it is getting in the way as development goes forward.  I've merged your changes into the feat-cmake branch and made some changes (set default build type, set CMAKE_RUNTIME_OUTPUT_DIRECTORY to build executeables in bin/, run tests in the build dir, use test labels to implement make simpletest, don't require yosys, etc.)  I have a few pending (minor) issues:
* How to portably determine compiler optimization flags for custom build type RelDebug.  (I want to build optimized without -DNDEBUG by default.)  I have no idea about this.
* Implement one of these solutions to portably require C++11:
https://stackoverflow.com/questions/10984442/how-to-detect-c11-support-of-a-compiler-with-cmake
* test or disallow in-source builds, see:
https://stackoverflow.com/questions/1208681/with-cmake-how-would-you-disable-in-source-builds
* need targets to build the example in examples/rot (rules to build a .bin from a .v's).
I will keep this branch up to date and will merge it in when I feel like I can comfortably add new build features.  Thanks again for our contribution!

**Comment by jhol** [comment]
@cseed - if you like I can look into these things. Would that be helpful? I've been following your work on this branch, and it looks like you're making progress.

Just a little word of advice - I hope you don't mind me giving it. I would recommend the advice in this article: ["Git Commit Hygene"](http://blog.ericbmerritt.com/2011/09/21/commit-hygiene-and-git.html).

I've noticed several commits in the project that are check-point commits; just a series of snapshots of work. I generally recommend not doing this; the history becomes much more meaningful when contributors have taken care to produce a series of atomic modifications. I highly recommend the use of `git add -p` - I use it to add all my changes to my commits, that way I know that my commit does just one thing with zero extraneous changes.

I feel a little bad sticking my oar in about this; but then in the end I think it's a helpful thing to do, and the thing about git history is that it is completely permanent.

If you would like, I can do a rebase tidy-up `feat-cmake` before you merge it.

**Comment by jhol** [comment]
@cseed So it looks like my branch has bit-rotted. I can update it if you like, but I was wondering if you agree with the concept of this patch? Do you actually want this change to go in? Personally I think having CMake would make quite an improvement for portability, but I don't want to go to the effort of rebuilding the branch if it's not going to merge.

**Comment by cseed** [comment]
@jhol First, let me say I greatly appreciate your contribution and I totally agree moving to CMake is a real improvement.  I have no intention of letting this branch drop and my plan was to update/integrate it after I finished PLL support.  I started a new job in July and I've had much less time to work on arachne than I would like.  Although I haven't announced it anywhere, PLL support is essentially done (people are using it without complaint) so now is a perfect time to revisit this branch.

If you update it, I will merge it straight away.  I just need it to pass Travis and verify I can build debug on Linux and OSX.

**Comment by jhol** [comment]
@cseed great! Thanks for updating me. I know how it feels. I've experienced something similar myself in the past few months.

I'll revisit the branch in the coming few days.

Also, I received my iCE40 HX8K board in the mail this week, so I'm finally able to actually test out the software with real hardware. I ran it up with the rot example (with some mods), and it worked perfectly.

Do you have any example code for the PLL config? That would be a good addition to the examples, I would say.

**Comment by cseed** [comment]
Great!

Here is an example from @SubProto to use it to generate a VGA pixel clock:  https://github.com/SubProto/icestick-vga-test/blob/master/vga.v

I agree.  I'll add examples for all the major hardware features.

**Comment by benpye** [comment]
@cseed Is this still something you want to move toward? I ask since I am interested in getting the toolchain needed for Ice40 parts compiling on Windows. I have managed to get arachne-pnr building using MSVC and I think MinGW should still work.

**Comment by jhol** [comment]
@benpye I would love someone to take this forward. It's probably needs some major rebasing by now, but the concept is good. Whatever happens the project should have exactly one build system in operation.

**Comment by benpye** [comment]
@jseed I agree. To clarify, that's using CMake to generate the MSVC solution.

**Comment by jhol** [comment]
Yeah CMake can make MSVC projects, Makefiles and my personal favourite Ninja-build files. None of these should be checked in of course- the use will generate the needed bus files when bootstrapping.

**Pull request closed without merging**
